version: '3.8'

services:
  sonar-lb:
    command:
      - --configFile=/traefik/conf.yml
    container_name: sonar-lb
    image: traefik:v2.3
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonar-lb.entrypoints=websecure
      - traefik.http.routers.sonar-lb.service=api@internal
      - traefik.http.routers.sonar-lb.rule=Host(`sonar-lb.qubiz.dev`)
      - traefik.http.routers.sonar-server.tls=true
      - traefik.http.routers.sonar-server.tls.certresolver=myresolver
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik:/traefik
    - storage-ssl:/certs
    networks:
    - sonar-net
    depends_on:
    - sonar-db

  sonar-server:
    image: sonarqube:8-community
    container_name: sonar-server
    env_file:
    - .env
    networks:
    - sonar-net
    labels:
    - traefik.enable=true
    - traefik.http.routers.sonar-server.entrypoints=websecure
    - traefik.http.routers.sonar-server.rule=Host(`sonar.qubiz.dev`)
    - traefik.http.routers.sonar-server.tls=true
    - traefik.http.routers.sonar-server.tls.certresolver=myresolver
    - traefik.http.routers.sonar-server.middlewares=test-redirectscheme
    - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
    - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
    volumes:
    - storage-sonar-data:/opt/sonarqube/data
    - storage-sonar-extensions:/opt/sonarqube/extensions
    depends_on:
    - sonar-lb

  sonar-db:
    image: postgres:13-alpine
    container_name: sonar-db
    env_file:
    - .env
    volumes:
    - sonar-db-data:/var/lib/postgresql/data
    networks:
    - sonar-net

volumes:
  storage-ssl:
    external: true
  storage-sonar-data:
    external: true
  storage-sonar-extensions:
    external: true
  sonar-db-data:
    external: true

networks:
  sonar-net:
    name: sonar-net